# Generated by Django 5.2.3 on 2025-06-11 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=120)),
                ('data_nasc', models.DateField()),
                ('observacoes', models.TextField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='perfil/alunos/')),
                ('responsavel', models.CharField(max_length=120)),
                ('cpf_responsavel', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=120)),
                ('cpf', models.CharField(max_length=11)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='perfil/colaboradores/')),
            ],
        ),
    ]
