# Generated by Django 5.2.3 on 2025-06-20 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=120)),
                ('descricao', models.TextField()),
                ('imagem', models.ImageField(upload_to='jogos/')),
            ],
        ),
    ]
