# Generated by Django 5.2.3 on 2025-06-20 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogo',
            name='descricao',
            field=models.TextField(max_length=120),
        ),
    ]
