# Generated by Django 5.2.3 on 2025-06-24 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogos', '0002_alter_jogo_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogo',
            name='descricao',
            field=models.TextField(max_length=1000),
        ),
    ]
